[workspace]
authors = ["Zshoham <ShohamZarfti@gmail.com>"]
channels = ["conda-forge"]
name = "deadpool"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=4.1.0,<5"
compilers = ">=1.11.0,<2"
llvm = ">=20.1.8,<21"
clang = ">=20.1.8,<21"
compiler-rt = ">=20.1.8,<21"
clang-tools = ">=20.1.8,<21"
gcovr = ">=8.3,<9"
just = ">=1.42.4,<2"
ninja = ">=1.13.1,<2"
