[workspace]
authors = ["Zshoham <ShohamZarfti@gmail.com>"]
channels = ["conda-forge"]
name = "deadpool"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=4.2.1,<5"
compilers = ">=1.11.0,<2"
llvm = ">=21.1.7,<22"
clang = ">=21.1.7,<22"
compiler-rt = ">=21.1.7,<22"
clang-tools = ">=21.1.7,<22"
gcovr = ">=8.3,<9"
just = ">=1.45.0,<2"
ninja = ">=1.13.2,<2"
clang-format = ">=21.1.7,<22"
